### ISSUE TITLE
Homework

### ISSUE THREAD

**Issue by HighspeedTrain1** [rstropek-teaching/turmrechnen-quiz-4bhif-ChristianWeber1#1]
https://stackblitz.com/edit/angular-ffj3pu

**Comment by rstropek** [comment]
Hi @ChristianWeber1 

You are nearly done. The result has to be formatted as a table. Change that and your extra point will be secured.

Greetings,
Rainer Stropek.

**Comment by HighspeedTrain1** [comment]
https://stackblitz.com/edit/angular-ffj3pu

I changed the result format to a table, thanks for the information!

**Comment by rstropek** [comment]
Nearly. If you take a close look at the spec you will see that the table consists of multiple columns that are nicely aligned. Do you know how you have to change your code to achieve that result?

**Comment by HighspeedTrain1** [comment]
I think I solved the problem

**Comment by rstropek** [comment]
@ChristianWeber1 Yes, looks nice. It would have been nice if you disabled the button if the form's content is invalid. However, that's a minor issue and your extra point is already secured.

Greetings,
Rainer Stropek.
